language: csharp

os: linux
dist: bionic
arch: amd64

mono: none
dotnet: 3.1.402
solution: UnityContainerAttributeRegistration.sln

git: 
  depth: false

script: 
  - dotnet restore
  - dotnet build --configuration Release --no-restore --verbosity minimal
  - dotnet test  --configuration Release --no-restore --verbosity minimal
