language: csharp

os: linux
dist: bionic
arch: amd64

mono: none
dotnet: 3.1.402
solution: UnityContainerAttributeRegistration.sln

addons: 
  sonarcloud:
    organization: "manticsic"
    token:
      secure: "YQE2S+Yq55EnlEezd3fUSmqGnHg2bH5LmC4wz8APD+/OzOJdTiVIk7dtv/ubKV0ZbTKFCbjwJUEXoxUnMhEuTAWdndTA71a/1dQq230BjD6HE95ul9BSsNp1E1+ZB/SmW1EztKSazugdmj8lqjvwhCJGT/QbKhwRzZaeLI+w1Rv588FjcnxGvu8odS26EGd+JvJiSbMBya9RRkvJHPmDUxRCTxStSFC7tcawFH7xOyexbT9rcJkZpdzetQ8c9a9eCHSaZyTVsMNJp+gdu4YEdUgUX2Rz32jvcmsbH+BRd2C+OBak8htWHv7qQM/ADviWJASs2ODjPIqmb2tTQnsMgorMrQRjI9QvuaMx2bpLUce1iGKjIGJOqv13/IKCMvAtG+uOa9hCoxTJxqm+XHLPkWtlhvDQQz2tjoqRyJ/+g0N8sw8rP5XuwdVDxSn0y1lQF3AwUilJt0TbVzAdzBDVb+DzNp3rhv2P6a8ahwfP73IdjRJWVHkXKnBeS7vtMwjGRCFUrUG1KO3ZmxYUaQjtL/oL0osm1S3q2ggCWCUVzlHmT7iYI3V8gm5femHryBeZ+FNp+ElAWNoQ3nXigIHKVoGX+DgtXHgNAga91F0/qW3ZrY/Y/NMOn1bFu6CIRizxxrBSU1peNmkYmirJtlfm5W+9Yk3UbHSxW9ePfcC7NgM="

git: 
  depth: false

script: 
  - dotnet restore
  - dotnet build --configuration release --no-restore --verbosity minimal
  - dotnet test  --configuration release --no-restore --verbosity minimal

before_deploy:
  - dotnet pack --configuration release --verbosity minimal -p:PackageVersion=$TRAVIS_TAG -p:RepositoryBranch=$TRAVIS_BUILD_NUMBER -p:RepositoryCommit=$TRAVIS_COMMIT -p:PackageOutputPath=.

deploy: 
  provider: releases
  api_key:
    secure: "cTfe+crP1MElj7/KDY1Kn86/oOK5n+9WnmNCDvLBOeaop4o1HKa4i76H4V+KCoPHqCHxrwCPdMmXSLtqp9GoFkZMmHbBsBKOGyDNyG6pE1AmUTLX897VgfdLiHfDIJsSu4rmOtdted5KTbqNdGjHll6CtZRS+PZ2dhW4NhenZtqnV/q9I9wjnWSUb+rTjZdexZKwiElpy/Dwdx2ZuWDsrnuQ8b8yRL+vNBp3LLvPYIsCZQFdpaM8f4u9cv7lzzcTnGZUJJtPOjyNnUDsH2EGLR3xyvP3GZcqnc6/aSKFvh0W82Mw+czqNW8yQVVZaUvABr8lwxTN2DWE18R561v7Y/JT7WMCLq0H1lVsBMeTfeTnSuMrZlYbunceHw1EOUwEzI4ywB97S5aistKvbUNZPvTFHvyCZGoWdDFqEEJX4xAUfKs0Fp3GsWgMz0USts+4rNiD8qFwyxxVBpR3kON1T7Nn2pGce3j72h3SCCZXruspsSHWXkiRjRTrAR+oxkHdp/nbjlGI8iE6/VichAb3c9PyWWyvhRsmfq+GuTLTRMYbw/w4BP1/kd4cnikzK1h6om4H8ZJM8jD7aolFMOt9W0EoTma8nwpffJoIeTXIf/PFvlhTraQhHHbceodBCyzcmykFI/KJXdYJc57NHDQj1yMqnlUV9HPtxfeWk0on21s="
  file_glob: true
  file: "./**/*.nupkg"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
