language: csharp

os: linux
dist: bionic
arch: amd64

mono: none
dotnet: 3.1.402
solution: UnityContainerAttributeRegistration.sln

addons: 
  sonarcloud:
    organization: "manticsic"
    token:
      secure: "YQE2S+Yq55EnlEezd3fUSmqGnHg2bH5LmC4wz8APD+/OzOJdTiVIk7dtv/ubKV0ZbTKFCbjwJUEXoxUnMhEuTAWdndTA71a/1dQq230BjD6HE95ul9BSsNp1E1+ZB/SmW1EztKSazugdmj8lqjvwhCJGT/QbKhwRzZaeLI+w1Rv588FjcnxGvu8odS26EGd+JvJiSbMBya9RRkvJHPmDUxRCTxStSFC7tcawFH7xOyexbT9rcJkZpdzetQ8c9a9eCHSaZyTVsMNJp+gdu4YEdUgUX2Rz32jvcmsbH+BRd2C+OBak8htWHv7qQM/ADviWJASs2ODjPIqmb2tTQnsMgorMrQRjI9QvuaMx2bpLUce1iGKjIGJOqv13/IKCMvAtG+uOa9hCoxTJxqm+XHLPkWtlhvDQQz2tjoqRyJ/+g0N8sw8rP5XuwdVDxSn0y1lQF3AwUilJt0TbVzAdzBDVb+DzNp3rhv2P6a8ahwfP73IdjRJWVHkXKnBeS7vtMwjGRCFUrUG1KO3ZmxYUaQjtL/oL0osm1S3q2ggCWCUVzlHmT7iYI3V8gm5femHryBeZ+FNp+ElAWNoQ3nXigIHKVoGX+DgtXHgNAga91F0/qW3ZrY/Y/NMOn1bFu6CIRizxxrBSU1peNmkYmirJtlfm5W+9Yk3UbHSxW9ePfcC7NgM="

git: 
  depth: false

script: 
  - dotnet restore
  - dotnet build --configuration release --no-restore --verbosity minimal
  - dotnet test  --configuration release --no-restore --verbosity minimal

before_deploy:
  - dotnet pack --configuration release --verbosity minimal -p:PackageVersion="${TRAVIS_TAG}.${$TRAVIS_BUILD_NUMBER}" -p:RepositoryBranch=$TRAVIS_BRANCH -p:RepositoryCommit=$TRAVIS_COMMIT -p:PackageOutputPath=.

deploy: 
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: "bin/Release/UnityContainerAttributeRegistration.${$TRAVIS_TAG}.nupkg"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    
after_deploy: 
  - dotnet nuget add source https://nuget.pkg.github.com/ManticSic/index.json -n github -u ManticSic -p $GH_TOKEN
  - dotnet nuget push "bin/Release/UnityContainerAttributeRegistration.${TRAVIS_TAG}.nupkg" --source "github"
